export const userConstants = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
};

export const apiConstants = {
  HOST: 'http://localhost:9090/v0.1.0',
};

export const uiConstants = {
  SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
  HIDE_LOGIN_MODAL: 'HIDE_LOGIN_MODAL',
  SHOW_REGISTER_MODAL: 'SHOW_REGISTER_MODAL',
  HIDE_REGISTER_MODAL: 'HIDE_REGISTER_MODAL',
  SHOW_ADD_CAR_MODAL: 'SHOW_ADD_CAR_MODAL',
  HIDE_ADD_CAR_MODAL: 'HIDE_ADD_CAR_MODAL',
  SHOW_EDIT_CAR_MODAL: 'SHOW_EDIT_CAR_MODAL',
  HIDE_EDIT_CAR_MODAL: 'HIDE_EDIT_CAR_MODAL',
};

export const carsConstants = {
  GET_CARS: 'GET_CARS',
  GET_CARS_SUCCESS: 'GET_CARS_SUCCESS',
  ADD_CAR: 'ADD_CAR',
  ADD_CAR_SUCCESS: 'ADD_CAR_SUCCESS',
  ADD_CAR_FAIL: 'ADD_CAR_FAIL',
  EDIT_CAR: 'EDIT_CAR',
  EDIT_CAR_SUCCESS: 'EDIT_CAR_SUCCESS',
  EDIT_CAR_FAIL: 'EDIT_CAR_FAIL',
  REMOVE_CAR: 'REMOVE_CAR',
  REMOVE_CAR_SUCCESS: 'REMOVE_CAR_SUCCESS',
  REMOVE_CAR_FAIL: 'REMOVE_CAR_FAIL',
}
