export const userConstants = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
};

export const apiConstants = {
  HOST: 'http://localhost:9090/v0.1.0',
};

export const uiConstants = {
  SHOW_LOGIN_MODAL: 'SHOW_LOGIN_MODAL',
  HIDE_LOGIN_MODAL: 'HIDE_LOGIN_MODAL',
  SHOW_REGISTER_MODAL: 'SHOW_REGISTER_MODAL',
  HIDE_REGISTER_MODAL: 'HIDE_REGISTER_MODAL',
};
